### ISSUE TITLE
Move at_utils package to at_libraries

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_libraries#359]
```[tasklist]
### Tasks
- [x] Check for an open PRS
- [x] Copy all of the git history over to at_libraries
- [ ] Change the repository URL in the pubspec and republish
```
