### ISSUE TITLE
Move at_commons package into at_libraries

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_libraries#360]
```[tasklist]
### Tasks
- [x] Check for an open PRS
- [x] Copy all of the git history over to at_libraries
- [ ] Change the repository URL in the pubspec and republish
```

**Comment by xavierchanth** [comment]
Waiting on some branches to be merged first.
